# Generated by Django 5.0.6 on 2024-06-02 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BoardData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('last_lti_date', models.DateField()),
                ('days_without_lti', models.IntegerField()),
                ('this_year_lti', models.IntegerField()),
            ],
        ),
    ]
